name: Run tests
on:
  pull_request:
    branches:
    - master
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run tests
      run: dotnet test TryReturn.sln